# ============================================================================
#
# IP-Check v3-SNAPSHOT    Authors; Jnk1296, dordsor21
# For more information visit http://dev.bukkit.org/server-mods/ip-check-jnk/
#
# IT IS RECOMMENDED THAT YOU READ THE CONFIGURATION EXPLANATION BEFORE MAKING
# MODIFICATIONS TO ANY OF THESE VALUES.
#
# Configuration Explanation can be found at;
# http://dev.bukkit.org/bukkit-plugins/ip-check-jnk/pages/default-configuration/
#
# MySQL pooling functions provided by c3p0.
#
# This product includes GeoLite data created by MaxMind, available from;
# http://www.maxmind.com/
#
# ============================================================================

# Localization Language Selection
# Default language is english if empty or "en".
# To switch language put in the name of the language-file (e.g. "de" for de.yml)
language: "en"

# Use MySQL instead of SQLite?
use-mysql: false

# Login details if backend is mysql
dbUsername: "root"
dbPassword: ""
dbHostname: "127.0.0.1"
dbName: "ip-check"
dbPort: 3306

# Set this to false if you want the tables to be regenerated
dbGenerated: false

# Should use Login Checking?
notify-on-login: true

# Should show descriptive notifications?
descriptive-notice: false

# Should use Secure Mode?
# Secure Mode is a feature of IP-Check that actively monitors and blocks
# players from making too many accounts on your server (limit controlled by
# secure-kick-threshold).
secure-mode: false

# Set a minimum number of accounts to have before being kicked
secure-kick-threshold: 1

# Set Secure Kick Message
secure-kick-message: "Multiple Accounts Not Permitted."

# Disable Update Detection
disable-update-detection: false

# Disable Metrics Monitoring
disable-metrics-monitoring: false

# GeoIP Services Main Control
use-geoip-services: true

# Allow IP-Check to automatically download the GeoIP Database
allow-geoip-download: true

# MC Hammer!
config-version: 1
