name: IP-Check
main: net.risenphoenix.ipcheck.IPCheck
version: 3.0-RELEASE
loadbefore: [AuthMe, xAuth, LoginSecurity, vAuth]
commands:
   ipc:
      description: Check for multi-accounting players via IP-Address or Player Name
      permission: ipcheck.use
      permission-message: You don't have permission to use this command. Please contact your server administrator.
